### ISSUE TITLE
export 'ɵa' (imported as 'i1') was not found in 'ngx-intl-tel-input'

### ISSUE THREAD

**Issue by imjaninerd** [webcat12345/ngx-intl-tel-input#93]
Can you help me with this warning I get upon running **npm run build:prod:aot** 

```
WARNING in ./src/$$_gendir/node_modules/ngx-intl-tel-input/ngx-intl-tel-input.ngfactory.ts
205:267-272 "export 'ɵa' (imported as 'i1') was not found in 'ngx-intl-tel-input'
    at HarmonyImportSpecifierDependency._getErrors (D:\Projects\samproject\svc_web_app\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\Projects\samproject\svc_web_app\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\Projects\samproject\svc_web_app\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (D:\Projects\samproject\svc_web_app\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (D:\Projects\samproject\svc_web_app\node_modules\webpack\lib\Compiler.js:512:17)
    at D:\Projects\samproject\svc_web_app\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\Projects\samproject\svc_web_app\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (D:\Projects\samproject\svc_web_app\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by saiidabs** [comment]
your not the only one who cant build for prod, did u find a fix for it?

**Comment by imjaninerd** [comment]
Still shows when I build in aot. I hope somebody here can help come up w/ a tweak for this.

**Comment by kiranagre** [comment]
@imjaninerd did u got the solution?

**Comment by Pratap-chauhan** [comment]
i am also facing this issue , if anybody have a solution please help me
